In [1]:
from pathlib import Path

import pandas as pd

import sys; sys.path.append('..')
import config as cfg

%load_ext autoreload
%autoreload 2

In [6]:
# whether to use expression or rppa data
# data_type = 'expression'
data_type = 'rppa'

# number of features to subset to, by mean absolute deviation
subset_mad_feats = 100

### Load expression data

We'll also subset to the top features by mean absolute deviation, if necessary.

In [7]:
expression_data_file = (
    '/home/jake/research/mpmp/data/tcga_expression_matrix_processed.tsv.gz'
)
expression_sample_info = (
    '/home/jake/research/mpmp/data/sample_info/tcga_expression_sample_identifiers.tsv'
)

rppa_data_file = (
    '/home/jake/research/mpmp/data/tcga_rppa_matrix_processed.tsv'
)
rppa_sample_info = (
    '/home/jake/research/mpmp/data/sample_info/tcga_rppa_sample_identifiers.tsv'
)

if data_type == 'expression':
    data_df = pd.read_csv(expression_data_file, sep='\t', index_col=0)
    sample_info_df = pd.read_csv(expression_data_file, sep='\t', index_col=0)
elif data_type == 'rppa':
    data_df = pd.read_csv(rppa_data_file, sep='\t', index_col=0)
    sample_info_df = pd.read_csv(rppa_data_file, sep='\t', index_col=0)
    
print(data_df.shape)
data_df.iloc[:5, :5]

(7790, 189)

                 X1433EPSILON  X4EBP1  X4EBP1_pS65  X4EBP1_pT37T46  X53BP1
sample_id
TCGA-OR-A5J2-01        -0.494   0.592      0.10500        -0.13500    1.89
TCGA-PA-A5YG-01        -0.535   0.183     -0.10600        -0.04010    1.03
TCGA-OR-A5JV-01        -0.109   0.418      0.02470        -0.72100    1.66
TCGA-OR-A5JT-01        -0.413   0.259      0.00597         0.56300    1.46
TCGA-OR-A5JR-01        -0.288  -0.112      0.01940        -0.00267    2.23

In [10]:
if subset_mad_feats is not None:
    mad_ranking = (
        data_df.mad(axis=0)
               .sort_values(ascending=False)
    )
    top_feats = mad_ranking[:subset_mad_feats].index.astype(str).values
    print(top_feats[:5])
    data_df = data_df.reindex(top_feats, axis='columns')
    
print(data_df.shape)
data_df.head()

['MYH11' 'VHL' 'ECADHERIN' 'ERALPHA' 'CLAUDIN7']
(7790, 100)

,MYH11,VHL,ECADHERIN,ERALPHA,CLAUDIN7,ACETYLATUBULINLYS40,RICTOR,FASN,CAVEOLIN1,GAPDH,...,MSH2,AKT,LCK,KU80,P53,SMAD1,NCADHERIN,G6PD,BAP1C4,TSC1
sample_id,,,,,,,,,,,,,,,,,,,,,
TCGA-OR-A5J2-01,1.950,-0.315,-1.400,-1.020,0.141,2.48,0.881,0.2280,2.160,1.550,...,-0.263,0.696,-0.0920,1.68,-0.743,0.0846,-0.24500,-0.5090,-0.427,2.25
TCGA-PA-A5YG-01,0.602,0.697,-0.223,-0.445,0.517,1.36,0.305,-0.6990,0.762,0.587,...,-0.266,0.543,-0.0364,1.44,-0.133,-0.1770,-0.18100,-0.2940,-0.531,1.11
TCGA-OR-A5JV-01,-0.679,-0.301,-1.350,-1.160,0.336,2.22,0.571,-0.2000,0.501,1.960,...,-0.402,0.437,0.2060,1.32,-0.437,0.1150,-0.25100,0.0225,-0.301,2.01
TCGA-OR-A5JT-01,-0.140,-0.481,-1.670,-1.210,0.204,2.75,0.141,-0.9400,1.450,0.503,...,-0.611,0.533,0.3390,1.10,-0.749,0.0357,0.04950,0.7790,-0.912,1.51
TCGA-OR-A5JR-01,-1.040,-0.337,-1.230,-1.090,0.265,3.04,0.331,-0.0643,0.708,1.670,...,-0.470,1.190,0.0180,1.15,-0.669,-0.1130,-0.00368,1.0000,-0.631,1.31

### Load sample-wise mutation data for Park et al. genes

This was computed and saved in `3_park_analysis.ipynb`.

In [11]:
# load park et al. initial analysis results here
park_info_df = pd.read_csv(
    cfg.park_info_file, sep='\t'
)

print(park_info_df.shape)
park_info_df.head()

(308148, 7)

,sample_id,positive_prob,identifier,mutation_status,copy_status,status,class
0,TCGA-4E-A92E-01,1.558183e-08,ACVR1_UCEC,0,0.0,none,class 1
1,TCGA-A5-A0GB-01,2.734236e-237,ACVR1_UCEC,1,0.0,one,class 1
2,TCGA-A5-A0GJ-01,0.000000e+00,ACVR1_UCEC,0,0.0,none,class 1
3,TCGA-A5-A0GM-01,0.000000e+00,ACVR1_UCEC,0,0.0,none,class 1
4,TCGA-A5-A0GW-01,0.000000e+00,ACVR1_UCEC,0,0.0,none,class 1